backend/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.urls.conf import include  
from django.conf import settings  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('profile/', include ('django.contrib.auth.urls')),
    path('profile/', include ('profiles.urls', namespace='profiles')),
    path("__reload__/", include("django_browser_reload.urls")),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

backend/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.header, name='home'),
    path('newpost', views.create_post, name='newpost'),
    path('search', views.search, name='search'),
    path('inquiry', views.create_inquiry, name='create_inquiry'),
    path('search/results', views.search_results, name='search_results'),
    path('search/<slug:table_name>/<int:page_number>', views.search, name='search'),
    path('<slug:table_name>/<int:product_id>', views.object_detailed, name='object_detailed'),
    path('delete/posts/<int:post_id>/<int:comment_id>', views.delete_comment, name='delete')
]

backend/pages/templates/pages/companies_details.html
{% extends 'pages/header.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/details.css' %}">


<div class="central">
    <h1>{{ object.name }}</h1>
    <img src='/media/{{ object.image }}' id="logo" alt="Company logo"/>
    <div class="form-label col"><p class="label">License number: </p><span class="post-span">{{ object.license_number }}</span></div>
    <div class="form-label col"><p class="label">Address: </p><span class="post-span">{{ object.address }}</span></div>
    <div class="form-label col"><p class="label">Zip: </p><span class="post-span">{{ object.zip }}</a></span></div>
    <div class="form-label col"><p class="label">Phone number: </p><span class="post-span">{{ object.phone_number }}</span></div>
    <div class="form-label col"><p class="label">Email: </p><span class="post-span">{{ object.email }}</span></div>
    <div class="form-label col"><p class="label">License status: </p><span class="post-span">{{ object.license_status }}</span></div>
    <h2>Employees</h2>

    {% if objects %}
    <table>
        <tr>
            <th style="width: 25%;">First name</th>
            <th style="width: 25%;">Last name</th>
            <th style="width: 25%;">Position</th>
            <th style="width: 25%;">Phone number</th>
        </tr>
        
        {% for member in objects %}
        <tr class='row' onclick="window.location='/members/{{ member.id }}';">
            <td>{{ member.first_name }}</td>
            <td>{{ member.last_name }}</td>
            <td>{{ member.position }}</td>
            <td>{{ member.phone_number }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h3>Company doesn't have registered employees at this moment.</h3>
    {% endif %}
</div>

{% endblock %}

backend/pages/templates/pages/create_inquiry.html
{% extends 'pages/header.html' %}
{% load static %}

{% block title %} New inquiry {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/newpost.css' %}">

<div class="container"> 
    {% if submitted %}
        <h3 id="confirmation">Your information was submitted.</h3>
        <a href="/inquiry"><button class="btn" >Post another</button></a>
    {% else %}
        <h1 class="form-title">Create new inquiry</h1>
        <form method="post" enctype="multipart/form-data"> 
            {% csrf_token %}
            
            {{ form.as_p }}
            <button class="btn" type="submit">Submit</button>
        </form>
    {% endif %}
</div>

 {% endblock %}

backend/pages/templates/pages/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Unpaid{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'pages/header.css' %}">
</head>
<body>
    <div id="header">
        <div id="menu">
            <a class="menu-button" href="/">Home</a>
            <a class="menu-button" href="/search/posts/0">Posts</a>
            <a class="menu-button" href="/newpost">Create post</a>
            <a class="menu-button" href="/profile">My Profile</a>
            {% if user.is_authenticated %}
                <a class="menu-button" href="/profile/logout_user">Logout</a>
            {% else %}
                <a class="menu-button" href="/profile/login">Login</a>
            {% endif %}
        </div>
    </div>
    <div id="content">
        {% block content %} 
        <div id="intro">
        <h1>Prototype of service 'Unpaid'</h1> 
        <p id="intro-text">Customer's rights are highly protected to ensure fair and satisfactory service experiences. On the other hand, service providers often have fewer protections. They face a challenge such as late or non-payment. While there are some legal remedies available, the burden of proof and the costs involved can be significant, making it challenging for service providers to assert their rights effectively. And some people take advantage of that.</p>
        <p id="intro-text">The main idea of "Unpaid" is to solve that issue and assist contractors in establishing a database of customers who have not made payment for provided services. It allows servicers to create a list of unpaid jobs, verify if existing or potential customers have a history of non-payment or issues with previous contractors.</p>
        </div>
        {% endblock %}
    </div>

</body>
</html>

backend/pages/templates/pages/inquiries_details.html
{% extends 'pages/header.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/details.css' %}">

<div class="post">
    <h1>{{ object.title }}</h1>
    <div class="inquiry-form-label col"><p class="label">Author: </p><span class="post-span"><a href="/members/{{ member.id }}">{{ object.author }}</a></span></div>
    <div class="inquiry-form-label col"><p class="label">Post reference: </p><span class="post-span"><a href="/posts/{{ post.id }}">{{ object.post }}</a></span></div>
    {% if object.attachment %}
    <div class="inquiry-form-label col"><p class="label">Attachment: </p><span class="post-span"><a href="/media/{{ object.attachment }}" target="_blank">View</a></span></div>
    {% endif %}
    <div class="inquiry-form-label col"><p  class="label">Desription: </p><span class="post-span">{{ object.body }}</span></div>
</div>

{% endblock %}

backend/pages/templates/pages/members_details.html
{% extends 'pages/header.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/profile.css' %}">

<h1 class="form-title">{{ object.username }}'s account</h1>
<div id="layout">
    <div class="profile-column">

    </div>
    <div class=" central">
        <div id="info">
            <p class="form-label">Username: <span class="profile-span">{{ object.username }}</span></p>
            <p class="form-label">First name: <span class="profile-span">{{ object.first_name }}</span></p>
            <p class="form-label">Last name: <span class="profile-span">{{ object.last_name }}</span></p>
            <p class="form-label">Email: <span class="profile-span">{{ object.email }}</span></p>
            {% if object.is_contractor %}
            <p class="form-label">Contractor: <span class="profile-span">Yes</span></p>
            {% else %}
            <p class="form-label">Contractor: <span class="profile-span">No</span></p>
            {% endif %}
            {% if object.is_contractor %}
                {% if object.company %}
                <p class="form-label">Company: <span class="profile-span">{{ object.company }}</span></p>
                {% endif %}
                {% if object.position %}
                <p class="form-label">Position: <span class="profile-span">{{ object.position }}</span></p>
                {% endif %}
            {% else %}
                {% if object.phone_number %}
                    <p class="form-label">Phone number: <span class="profile-span">{{ object.phone_number }}</span></p>
                {% endif %}
                {% if object.address or object.zip %}
                    <p class="form-label">Address: <span class="profile-span">{{ object.address }}, {{ object.zip }}</span></p>
                {% endif %}
            {% endif %}

        </div>
        </a>
    </div>
    <div class="tables">
        {% if current_member.is_contractor %}
        <h2> {{ object.username }}'s posts</h2>
        <table>
            <tr>
                <th style="width: 30%;">Invoice</th>
                <th style="width: 30%;">Title</th>
                <th style="width: 40%;">Service provided</th>
            </tr>
            
            {% for post in posts %}
            <tr class='row' onclick="window.location='/posts/{{ post.id }}';">
                <td>{{ post.invoice_number }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.service_provided }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}

        <h3>{{ object.username }}'s inquiries</h3>
        <table>
            <tr>
                <th style="width: 10%;">Id</th>
                <th style="width: 45%;">Title</th>
                <th style="width: 45%;">Post</th>
            </tr>
            
            {% for inquiry in inquiries %}
            <tr class='row' onclick="window.location='/inquiries/{{ inquiry.id }}';">
                <td>{{ inquiry.id }}</td>
                <td>{{ inquiry.title }}</td>
                <td>{{ inquiry.post }}</td>

            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

backend/pages/templates/pages/newpost.html
{% extends 'pages/header.html' %}
{% load static %}

{% block title %} New post {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/newpost.css' %}">

{% if member.is_contractor and company_status %}
    <div class="container"> 
        {% if submitted %}
            <h3 id="confirmation">Your information was submitted.</h3>
            <a href="/newpost"><button class="btn" >Post another</button></a>
        {% else %}
            <h1 class="form-title">Create new post</h1>
            <form method="post" enctype="multipart/form-data"> 
                {% csrf_token %}
                
                {{ form.as_p }}
                <button class="btn" type="submit">Submit</button>
            </form>
        {% endif %}
    </div>
{% else %}
    <h1><br/>Only contractors with active license can create a new posts.</h1>
{% endif %}

 {% endblock %}

backend/pages/templates/pages/posts.html
{% extends 'pages/header.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/posts.css' %}">
<div id="container">
    <div id="buttons-area">
        <button class="btn" onclick="location.href='/search/inquiries/0'">Inquiries</button>
        <button class="btn" onclick="location.href='/search/companies/0'">Companies</button>
        <button class="btn" onclick="location.href='/search/posts/0'">Posts</button>
    </div>
    <div id="search-area">
        <div id="search-tools">
            <div>
                {% if table == "posts" %}
                <form id="search-form" method="POST" action="{% url 'pages:search_results' %}">
                    {% csrf_token %}

                    <input id="search-field" type="search" placeholder="Post search" name="search">
                    <button id="search-btn">Search</button>
                </form>
                {% endif %}
            </div>
            <div id="arrows">
                {% if page_number == 0 %}
                <button class="page-selector" id="backward" disabled><</button>
                {% else %}
                <button class="page-selector" id="backward"><</button>
                {% endif %}
                {% if is_last %}
                <button class="page-selector" id="forward" disabled>></button>
                {% else %}
                <button class="page-selector" id="forward">></button>
                {% endif %}
            </div>
        </div>
        {% if table == 'posts' %} 
        <table>
            <tr>
                <th style="width: 15%;">Invoice</th>
                <th style="width: 20%;">Title</th>
                <th style="width: 45%;">Service provided</th>
                <th style="width: 10%;">Amount</th>
                <th style="width: 10%;">Author</th>
            </tr>
            
            {% for object in objects %}
            <tr class='row' onclick="window.location='/{{table}}/{{ object.id }}';">
                <td>{{ object.invoice_number }}</td>
                <td>{{ object.title }}</td>
                <td>{{ object.service_provided }}</td>
                <td>{{ object.amount }}</td>
                <td>{{ object.author}}</td>
            </tr>
            {% endfor %}
        </table>
        {% elif table == 'inquiries' %}
        <table>
            <tr>
                <th style="width: 10%;">Id</th>
                <th style="width: 15%;">Title</th>
                <th style="width: 50%;">Body</th>
                <th style="width: 10%;">Author</th>
                <th style="width: 15%;">Post</th>
            </tr>
            
            {% for object in objects %}
            <tr class='row' onclick="window.location='/{{table}}/{{ object.id }}';">
                <td>{{ object.id }}</td>
                <td>{{ object.title }}</td>
                <td>{{ object.body }}</td>
                <td>{{ object.author}}</td>
                <td>{{ object.post }}</td>
            </tr>
            {% endfor %}
        </table>
        {% elif table == 'companies' %}
        <table>
            <tr>
                <th style="width: 20%;">Name</th>
                <th style="width: 20%;">License number</th>
                <th style="width: 20%;">Address</th>
                <th style="width: 20%;">Phone number</th>
                <th style="width: 20%;">License status</th>
            </tr>
            
            {% for object in objects %}
            <tr class='row' onclick="window.location='/{{table}}/{{ object.id }}';">
                <td>{{ object.name }}</td>
                <td>{{ object.license_number }}</td>
                <td>{{ object.address }}</td>
                <td>{{ object.phone_number }}</td>
                <td>{{ object.license_status}}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>

<script>
    const backward = document.getElementById('backward')
    let previousPage = Number('{{page_number}}') - 1
    backward.addEventListener("click", () => {
            window.location.href = `/search/{{table}}/${previousPage}`;
        });

    const forward = document.getElementById('forward')
    let nextPage = Number('{{page_number}}') + 1
    console.log(nextPage)
    forward.addEventListener("click", () => {
            window.location.href = `/search/{{table}}/${nextPage}`;
        });

</script>
{% endblock %}

backend/pages/templates/pages/posts_details.html
{% extends 'pages/header.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/details.css' %}">

<div class="post">
    <h1>{{ object.title }}</h1>
    <div class="inquiry-form-label col"><p class="label">Service provided: </p><span class="post-span">{{ object.service_provided }}</span></div>
    <div class="inquiry-form-label col"><p class="label">Contractor: </p><span class="post-span"><a href="/members/{{ post_author.id }}">{{ object.author }}</a></span></div>
    <div class="inquiry-form-label col"><p class="label">Invoice number: </p><span class="post-span">{{ object.invoice_number }}</span></div>
    <div class="inquiry-form-label col"><p class="label">Amount: </p><span class="post-span">{{ object.amount }}</span></div>
    <div class="inquiry-form-label col"><p class="label">Customer info: </p><span class="post-span">{{ object.customer_info }}</span></div>
    <div class="inquiry-form-label col"><p class="label">Invoice photo: </p><span class="post-span"><a href="/media/{{ object.invoice_photo }}" target="_blank">View</a></span></div>
    <div class="inquiry-form-label col"><p  class="label">Desription: </p><span class="post-span">{{ object.description }}</span></div>
</div>

<button id="scroll-btn" onclick="scrollToBottom()">Scroll to the end</button>

<div id="comment-section">
    <div id="comments-container">
        {% for comment in comments %}
            <div class="comments"> 
                <div class="comment-head">
                    <div class="head-container">
                        <span class="comment-author">
                            <a href="/members/{{ comment.author.id }}">{{ comment.author }}</a> 
                            {% if comment.attachment %}
                            <a class="link" href="/media/{{ comment.attachment }}"><img src="/media/invoices/attachment.png" width="20"></a>
                            {% endif %}
                        </span>
                    </div>
                    <div>
                        <span class="timestamp"> {{ comment.created_at }}</span>
                        {% if current_user == comment.author.username %}
                        <button class="delete" onclick="window.location='/delete{{ path }}/{{ comment.id }}';">X</button>
                        {% endif %}
                    </div>
                </div>
                <p>{{ comment.body }}</p>
            </div>
        {% endfor %}
    </div>
    <div id="comment">
        <form method="post" enctype="multipart/form-data"> 
            {% csrf_token %}

            {{ form.as_p }}
            <button id="send" type="submit">Send</button>
        </form>
    </div>
</div>

<script>
    function scrollToBottom() {
      const element = document.getElementById("comment");
      element.scrollIntoView({behavior: 'smooth'});
    }
</script>
{% endblock %}

backend/pages/templates/pages/results.html
{% extends 'pages/header.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/posts.css' %}">
<div id="container">
    <div id="buttons-area">
        <button class="btn" onclick="location.href='/search/inquiries/0'">Inquiries</button>
        <button class="btn" onclick="location.href='/search/companies/0'">Companies</button>
        <button class="btn" onclick="location.href='/search/posts/0'">Posts</button>
    </div>
    <div id="search-area">
        <div id="search-tools">
            <div>
                {% if table == "posts" %}
                <form id="search-form" method="POST" action="{% url 'pages:search_results' %}">
                    {% csrf_token %}

                    <input id="search-field" type="search" placeholder="Post search" name="search">
                    <button id="search-btn">Search</button>
                </form>
                {% endif %}
            </div>
            <div id="arrows">
                <button class="page-selector" id="backward" disabled><</button>
                <button class="page-selector" id="forward" disabled>></button>
            </div>
        </div>

        {% if results %}
        <table>
            <tr>
                <th style="width: 15%;">Invoice</th>
                <th style="width: 20%;">Title</th>
                <th style="width: 45%;">Service provided</th>
                <th style="width: 10%;">Amount</th>
                <th style="width: 10%;">Author</th>
            </tr>
            {% for result in results %}
            <tr class='row' onclick="window.location='/{{table}}/{{ object.id }}';">
                <td>{{ result.invoice_number }}</td>
                <td>{{ result.title }}</td>
                <td>{{ result.service_provided }}</td>
                <td>{{ result.amount }}</td>
                <td>{{ result.author}}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <table>
            <tr>
                <th style="width: 15%;">Invoice</th>
                <th style="width: 20%;">Title</th>
                <th style="width: 45%;">Service provided</th>
                <th style="width: 10%;">Amount</th>
                <th style="width: 10%;">Author</th>
            </tr>
        </table>
        <h2 style="text-align: center;"><br/>No match found!</h2>
        {% endif %}
    </div>
</div>

<script>
    const backward = document.getElementById('backward')
    let previousPage = Number('{{page_number}}') - 1
    backward.addEventListener("click", () => {
            window.location.href = `/search/results/${previousPage}`;
        });

    const forward = document.getElementById('forward')
    let nextPage = Number('{{page_number}}') + 1
    console.log(nextPage)
    forward.addEventListener("click", () => {
            window.location.href = `/search/results/${nextPage}`;
        });

</script>
{% endblock %}